# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        ("hotels", "0001_initial"),
        ("rates", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmation_number", models.CharField(max_length=20)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone"),
                            ("website", "Website"),
                            ("airbnb", "Airbnb"),
                            ("booking_com", "Booking.com"),
                            ("ota_other", "Other OTA"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                ("external_booking_id", models.CharField(blank=True, max_length=100)),
                ("num_adults", models.PositiveIntegerField(default=1)),
                ("num_children", models.PositiveIntegerField(default=0)),
                ("special_requests", models.TextField(blank=True)),
                ("actual_check_in_time", models.DateTimeField(blank=True, null=True)),
                ("actual_check_out_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="guests.guest",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "rate_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rates.rateplan",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_rooms",
                        to="rooms.room",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rooms.roomtype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomNightRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rate in INR for this night",
                        max_digits=10,
                    ),
                ),
                (
                    "reservation_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nightly_rates",
                        to="reservations.reservationroom",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["hotel", "status"], name="reservation_hotel_i_b9ee03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["hotel", "check_in_date"], name="reservation_hotel_i_859fcf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("hotel", "confirmation_number")},
        ),
        migrations.AddIndex(
            model_name="reservationroom",
            index=models.Index(
                fields=["room", "check_in_date", "check_out_date"],
                name="reservation_room_id_abe5da_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomnightrate",
            unique_together={("reservation_room", "date")},
        ),
    ]
