# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("ota", "OTA"),
                            ("corporate", "Corporate"),
                            ("promotional", "Promotional"),
                            ("long_stay", "Long Stay"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone"),
                            ("website", "Website"),
                            ("airbnb", "Airbnb"),
                            ("booking_com", "Booking.com"),
                            ("ota_other", "Other OTA"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority wins if multiple plans match",
                    ),
                ),
                ("min_stay_nights", models.PositiveIntegerField(default=1)),
                ("advance_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cancellation_policy",
                    models.CharField(
                        choices=[
                            ("free", "Free Cancellation"),
                            ("moderate", "Moderate"),
                            ("strict", "Strict"),
                            ("non_refundable", "Non-Refundable"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("cancellation_hours", models.PositiveIntegerField(default=24)),
                (
                    "cancellation_charge_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_plans",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["hotel", "-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="RatePlanRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="INR per night", max_digits=10
                    ),
                ),
                (
                    "extra_adult_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "extra_child_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="rates.rateplan",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_plan_rates",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "unique_together": {("rate_plan", "room_type")},
            },
        ),
        migrations.CreateModel(
            name="SeasonalRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Diwali Peak, Monsoon Off-Peak", max_length=100
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overrides base_rate for these dates",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rate_plan_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_rates",
                        to="rates.rateplanrate",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
