# Generated by Django 5.2.13 on 2026-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rateplan",
            name="cancellation_charge_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
