# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("hotels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for super_admin (sees all hotels)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
