# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. MUM01", max_length=10, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("max_rooms", models.PositiveIntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OTAConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("airbnb", "Airbnb"),
                            ("booking_com", "Booking.com"),
                            ("goibibo", "Goibibo"),
                            ("makemytrip", "MakeMyTrip"),
                            ("agoda", "Agoda"),
                            ("expedia", "Expedia"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("direct_api", "Direct API"),
                            ("channel_manager", "Channel Manager"),
                            ("ical", "iCal Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                ("channel_manager_name", models.CharField(blank=True, max_length=100)),
                ("external_property_id", models.CharField(blank=True, max_length=100)),
                ("api_key_id", models.CharField(blank=True, max_length=200)),
                ("ical_url", models.URLField(blank=True, max_length=500)),
                ("webhook_url", models.URLField(blank=True, max_length=500)),
                ("sync_bookings", models.BooleanField(default=True)),
                ("sync_rates", models.BooleanField(default=False)),
                ("sync_availability", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("never_synced", "Never Synced"),
                        ],
                        default="never_synced",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ota_connections",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["hotel", "channel"],
            },
        ),
    ]
