# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otaconnection",
            name="rate_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rates.rateplan",
            ),
        ),
    ]
