# Generated by Django 5.2.13 on 2026-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio_number", models.CharField(max_length=20)),
                (
                    "total_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_payments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("settled", "Settled"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FolioCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("room_charge", "Room Charge"),
                            ("cgst", "CGST"),
                            ("sgst", "SGST"),
                            ("igst", "IGST"),
                            ("food_beverage", "Food & Beverage"),
                            ("laundry", "Laundry"),
                            ("minibar", "Minibar"),
                            ("misc", "Miscellaneous"),
                            ("discount", "Discount"),
                            ("cancellation_fee", "Cancellation Fee"),
                            ("no_show_fee", "No Show Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive=charge, Negative=discount",
                        max_digits=10,
                    ),
                ),
                ("charge_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["charge_date", "created_at"],
            },
        ),
    ]
