# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("hotels", "0001_initial"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folio",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folios",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="folio",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folio",
                to="reservations.reservation",
            ),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foliocharge",
            name="folio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="billing.folio",
            ),
        ),
        migrations.AddIndex(
            model_name="folio",
            index=models.Index(
                fields=["hotel", "status"], name="billing_fol_hotel_i_5049b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foliocharge",
            index=models.Index(
                fields=["folio", "charge_date"], name="billing_fol_folio_i_46068c_idx"
            ),
        ),
    ]
