# Generated by Django 5.2.13 on 2026-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aadhar", "Aadhar Card"),
                            ("passport", "Passport"),
                            ("driving_license", "Driving License"),
                            ("voter_id", "Voter ID"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=50)),
                (
                    "id_document_front",
                    models.CharField(
                        blank=True, help_text="Cloud Storage path", max_length=500
                    ),
                ),
                (
                    "id_document_back",
                    models.CharField(
                        blank=True, help_text="Cloud Storage path", max_length=500
                    ),
                ),
                ("nationality", models.CharField(default="Indian", max_length=100)),
                ("is_foreign", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("form_a", "Form A"),
                            ("form_c", "Form C (Foreign Guest)"),
                            ("police_intimation", "Police Intimation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("verified_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
