# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("hotels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelPaymentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_key_id",
                    models.CharField(
                        blank=True, help_text="Public key (safe in DB)", max_length=50
                    ),
                ),
                (
                    "razorpay_account_id",
                    models.CharField(
                        blank=True, help_text="For Razorpay Route", max_length=50
                    ),
                ),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, help_text="Hotel GSTIN", max_length=20
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=4),
                ),
                ("sac_code", models.CharField(default="9963", max_length=10)),
                ("accepts_online_payment", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount in INR", max_digits=10
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("net_banking", "Net Banking"),
                            ("wallet", "Wallet"),
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("corporate", "Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("razorpay_order_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_signature", models.CharField(blank=True, max_length=200)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, help_text="For manual payments", max_length=100
                    ),
                ),
                ("refund_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.folio",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "original_payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links refund to original payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "status"],
                        name="payments_pa_hotel_i_0f69d6_idx",
                    )
                ],
            },
        ),
    ]
