# Generated by Django 5.2.13 on 2026-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. reservation.created, room.status_changed",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=50)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyAuditSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_date", models.DateField()),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                ("occupied_rooms", models.PositiveIntegerField(default=0)),
                (
                    "occupancy_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "revenue_posted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("noshow_count", models.PositiveIntegerField(default=0)),
                ("arrivals_tomorrow", models.PositiveIntegerField(default=0)),
                ("departures_tomorrow", models.PositiveIntegerField(default=0)),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-audit_date"],
            },
        ),
    ]
