# Generated by Django 5.2.13 on 2026-04-11 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("send_booking_confirm", models.BooleanField(default=True)),
                ("send_checkin_reminder", models.BooleanField(default=True)),
                ("send_payment_receipt", models.BooleanField(default=True)),
                ("send_checkout_summary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("staff", "Staff"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("recipient_phone", models.CharField(blank=True, max_length=15)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("in_app", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="MSG91 message ID", max_length=100
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("related_model", models.CharField(blank=True, max_length=50)),
                ("related_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "status"],
                        name="notificatio_hotel_i_37c3b0_idx",
                    )
                ],
            },
        ),
    ]
